### ISSUE TITLE
1.0.1: String encryption fails

### ISSUE THREAD

**Issue by kangarko** [ItzSomebody/Radon#31]
Trying to further obfuscate a Spigot plugin already obfuscated by ProGuard. This is the console output.

https://pastebin.com/Vpf9Kkgj

**Comment by kangarko** [comment]
Also, when removed String encryption, the obfuscator worked fine, but it failed to load as a plugin.

Radon console:
```
[09/03/2018-11:12:54] INFO: Loading library "C:\Program Files\Java\jre1.8.0_181\lib\rt.jar".
[09/03/2018-11:12:54] INFO: Loading library "C:\Program Files\Java\jre1.8.0_181\lib\jce.jar".
[09/03/2018-11:12:54] INFO: Loading library "D:\Java\Libraries\spigot_1.13.1.jar".
[09/03/2018-11:12:55] INFO: Loading library "D:\Java\Libraries\BungeeCord.jar".
[09/03/2018-11:12:55] INFO: Loading library "D:\Java\Libraries\Plugins\AuthMe-5.5.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\BlueShopAPI.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Boss.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\BossShop.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\ChestShop.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\DiscordSRV.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\EssentialsX.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Factions.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\FactionsOne.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\FactionsUUID.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Feudal.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Heroes.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Kingdoms.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\LWC.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\LegacyFactions.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Lockette.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\LockettePro.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\MVdWPlaceholderAPI.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\MarcelysBedwars.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\MassiveCore.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\MobArena.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Multiverse-Core-2.6.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\MythicMobs.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Nametags.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Nicky.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\PermissionsEx.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\PlaceholderAPI.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\PowerNBT.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\ProtocolLib.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\RedisBungee-0.4.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Residence.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\Shop.jar".
[09/03/2018-11:12:56] INFO: Loading library "D:\Java\Libraries\Plugins\ShopGUIPlus.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\SignShop.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\SimpleClans.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\Towny.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\Vault.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\Votifier.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\WorldEdit.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\WorldGuard.jar".
[09/03/2018-11:12:57] INFO: Loading library "D:\Java\Libraries\Plugins\mcMMO.jar".
[09/03/2018-11:12:57] INFO: Loading input "C:\Users\kangarko\workspace\ChatControl\target\ChatControl-7.9.17.jar".
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Running Shrinker transformer.
[09/03/2018-11:12:57] INFO: Removed 1013 inner classes, 58 outer classes, 43 outer methods, 106 class generic types, 603 method generic types and 199 field generic types.
[09/03/2018-11:12:57] INFO: Finished running Shrinker transformer. [16ms]
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Running Light invokedynamic transformer.
[09/03/2018-11:12:57] INFO: Replaced 20041 method invocations with invokedynamics.
[09/03/2018-11:12:57] INFO: Finished running Light invokedynamic transformer. [31ms]
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Running Light flow obfuscation transformer.
[09/03/2018-11:12:57] INFO: Added 2481 fake throw-null sequences
[09/03/2018-11:12:57] INFO: Finished running Light flow obfuscation transformer. [16ms]
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Running Source name transformer.
[09/03/2018-11:12:57] INFO: Removed 571 source name attributes.
[09/03/2018-11:12:57] INFO: Finished running Source name transformer. [0ms]
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Running Source debug transformer.
[09/03/2018-11:12:57] INFO: Removed 571 source debug attributes.
[09/03/2018-11:12:57] INFO: Finished running Source debug transformer. [0ms]
[09/03/2018-11:12:57] INFO: ------------------------------------------------
[09/03/2018-11:12:57] INFO: Writing output to "C:\Users\kangarko\Desktop\ChatControl_obfuscated.jar".
```

```
[11:13:10 ERROR]: Could not load 'plugins\ChatControl_obfuscated.jar' in folder
'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.BootstrapMethodError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:133) ~[patched_1.13.1.jar:git-Paper-197]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:329) ~[patched_1.13.1.jar:git-Paper-197]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:251) ~[patched_1.13.1.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.j
ava:322) ~[patched_1.13.1.jar:git-Paper-197]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.ja
va:230) ~[patched_1.13.1.jar:git-Paper-197]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:784) ~[patched_1.13.1.jar:git-Paper-197]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.BootstrapMethodError
        at me.kangarko.chatcontrol.kautils.reflections.DataMap$Metrics$MultiLine
Chart.??? (Unknown Source) ~[?:?]
        at java.lang.invoke.CallSite.makeSite(Unknown Source) ~[?:1.8.0_181]
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source)
 ~[?:1.8.0_181]
        at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) ~[?
:1.8.0_181]
        at me.kangarko.chatcontrol.ChatControl.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav
a:82) ~[patched_1.13.1.jar:git-Paper-197]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:129) ~[patched_1.13.1.jar:git-Paper-197]
        ... 6 more
```

**Comment by kangarko** [comment]
I have to correct, just noticed the plugin was NOT obfuscated by ProGuard, so we are dealing with a brand clear jar.

**Comment by kangarko** [comment]
When disabled Flow obfuscation, this is new Spigot error: https://pastebin.com/08DWV372

Here is radon console just to clarify: https://pastebin.com/yHD1cUCC

**Comment by ItzSomebody** [comment]
That's an issue with the invokedynamic transformer, I'll see what I can do. The string encryption error is a typo on my part, I'll make sure to get that fixed some time. Thanks!

**Comment by kangarko** [comment]
Thanks! Where can I donate?
