### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by apython123** [ItzSomebody/Radon#6]
0.6.1

bouncycastle  , a crypto library. bcprov-jdk15on-153.jar

Radon the issue.

https://pastebin.com/7cayzQ5W

in "- Writing classes to output".

My log in 665 line of Frame.java : inputStack.length=0, value=1
I try to repair it ,but I find some others error in Frames.java like "NegativeArraySizeException , ArrayIndexOutOfBoundsException: -1  , NullPointerException".

**Comment by ItzSomebody** [comment]
I need more details to look into what is causing the error. My most likely guess would be flow obf, but it's possible it could be ASM.

Which transformers did you use?

**Comment by ItzSomebody** [comment]
Closed this on accident.

**Comment by apython123** [comment]
config.yml:
Input: "bcprov-jdk15on-153.jar"
Output: "Counter-OBF.jar"
StringEncryption: Normal
InvokeDynamic: Heavy
FlowObfuscation: Normal
LocalVariableObfuscation: Remove
LineNumberObfuscation: Remove
SourceNameObfuscation: Remove
SourceDebugObfuscation: Remove
HideCode: True
Crasher: True
Shuffler: True
InnerClassRemover: True
StringPool: True
NumberObfuscation: True
TrashClasses: 50
Renamer: False
WatermarkType: ConstantPool
WatermarkMessage: ItzSomebody
WatermarkKey: PASSWORD
ExpiryTime: 5/25/2018

**Comment by apython123** [comment]
more information:
[04/24/2018-00:42:09] [Radon] - Version: 0.6.1
[04/24/2018-00:42:09] [Radon] - Authors: ItzSomebody
[04/24/2018-00:42:09] [Radon] - Successfully parsed config
[04/24/2018-00:42:09] [Radon] - Loading library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
[04/24/2018-00:42:10] [Radon] - Loading classes of /mnt/d/023obfuscate/radon/test/bcprov-jdk15on-153.jar
[04/24/2018-00:42:10] [Radon] - ------------------------------------------------
[04/24/2018-00:42:10] [Radon] - Started inner class removal transformer
[04/24/2018-00:42:10] [Radon] - Removed 2169 inner class infos.
[04/24/2018-00:42:10] [Radon] - Finished. [79ms]
[04/24/2018-00:42:10] [Radon] - ------------------------------------------------
[04/24/2018-00:42:10] [Radon] - Started number obfuscation transformer
[04/24/2018-00:42:19] [Radon] - Split 90896 numbers into bitwise xor instructions.
[04/24/2018-00:42:19] [Radon] - Finished. [8314ms]
[04/24/2018-00:42:19] [Radon] - ------------------------------------------------
[04/24/2018-00:42:19] [Radon] - Started heavy invokedynamic transformer
[04/24/2018-00:42:19] [Radon] - Hid 0 field and/or method accesses with invokedynamics.
[04/24/2018-00:42:19] [Radon] - Finished. [75ms]
[04/24/2018-00:42:19] [Radon] - ------------------------------------------------
[04/24/2018-00:42:19] [Radon] - Started expiry transformer
[04/24/2018-00:42:19] [Radon] - Added 3793 expiration code blocks.
[04/24/2018-00:42:19] [Radon] - Finished. [36ms]
[04/24/2018-00:42:19] [Radon] - ------------------------------------------------
[04/24/2018-00:42:19] [Radon] - Started normal string encryption transformer
[04/24/2018-00:42:34] [Radon] - Encrypted 13979 strings.
[04/24/2018-00:42:34] [Radon] - Finished. [14683ms]
[04/24/2018-00:42:34] [Radon] - ------------------------------------------------
[04/24/2018-00:42:34] [Radon] - Started normal flow obfuscation transformer
[04/24/2018-00:43:02] [Radon] - Added 41405 instruction sets.
[04/24/2018-00:43:02] [Radon] - Finished. [28189ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started string pool transformer.
[04/24/2018-00:43:02] [Radon] - Pooled  13979 strings.
[04/24/2018-00:43:02] [Radon] - Finished. [86ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started shuffle transformer
[04/24/2018-00:43:02] [Radon] - Shuffled 29838 members.
[04/24/2018-00:43:02] [Radon] - Finished. [9ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started local variable removal transformer
[04/24/2018-00:43:02] [Radon] - Removed 0 local variables.
[04/24/2018-00:43:02] [Radon] - Finished. [44ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started line removal transformer
[04/24/2018-00:43:02] [Radon] - Removed 0 line numbers.
[04/24/2018-00:43:02] [Radon] - Finished. [58ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started source name removal transformer
[04/24/2018-00:43:02] [Radon] - Removed 0 source name attributes.
[04/24/2018-00:43:02] [Radon] - Finished. [6ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started source debug removal transformer
[04/24/2018-00:43:02] [Radon] - Removed 0 source debug attributes.
[04/24/2018-00:43:02] [Radon] - Finished. [14ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started crasher transformer.
[04/24/2018-00:43:02] [Radon] - Added 2659 crashers.
[04/24/2018-00:43:02] [Radon] - Finished. [20ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Started hide code transformer
[04/24/2018-00:43:02] [Radon] - Hid 29910 members.
[04/24/2018-00:43:02] [Radon] - Finished. [49ms]
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Generated 50 trash classes
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Writing generated classes to output
[04/24/2018-00:43:02] [Radon] - ------------------------------------------------
[04/24/2018-00:43:02] [Radon] - Writing classes to output
[04/24/2018-00:43:02] [Radon] - Error while writing org/bouncycastle/crypto/params/DSAPrivateKeyParameters -> -1
[04/24/2018-00:43:02] [Radon] - Error happened while processing: -1
[04/24/2018-00:43:02] [Radon] - Deleted output.
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.objectweb.asm.Frame.getInitializedType(Frame.java:665)
        at org.objectweb.asm.Frame.merge(Frame.java:1190)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1633)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1569)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:838)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:718)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:426)
        at me.itzsomebody.radon.internal.Bootstrap.startTheParty(Bootstrap.java:255)
        at me.itzsomebody.radon.internal.CLI.startTheParty(CLI.java:71)
        at me.itzsomebody.radon.internal.CLI.<init>(CLI.java:32)
        at me.itzsomebody.radon.Radon.main(Radon.java:33)
[04/24/2018-00:43:02] [Radon] - Writing log.
java.lang.RuntimeException: -1
        at me.itzsomebody.radon.internal.Bootstrap.startTheParty(Bootstrap.java:297)
        at me.itzsomebody.radon.internal.CLI.startTheParty(CLI.java:71)
        at me.itzsomebody.radon.internal.CLI.<init>(CLI.java:32)
        at me.itzsomebody.radon.Radon.main(Radon.java:33)

**Comment by ItzSomebody** [comment]
This is probably a flow obf problem.

**Comment by apython123** [comment]
I dont know how to resolve it . Could you download jar
file from https://www.bouncycastle.org/latest_releases.html and reappear this problem.

**Comment by ItzSomebody** [comment]
I'm assuming this should be fixed for now, let me know if otherwise

**Comment by apython123** [comment]
Yes，It is fixed from 0.8.2.
