### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [ItzSomebody/Radon#61]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)** 1.0.5

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)** Standalone?

**What transformers did you use which caused an error?**
* None still causes this, i believe all settings off still cause this, cant confirm

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)** Dont understand this, i cant provide the jar but i will provide some of the code later.

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://pastebin.com/46eEngXv

**Any other information? (i.e. You combined Radon with other obfuscators)** no i dident combine anything

when i ran the obfuscated jar it would crash with a game
java.lang.VerifyError? Adding -noverify to the jvm fixed it, removing the class, LogOutSpot would fix the error, my code WHERE IT ERRORS, is,
```java
@EventTarget
	  public void onPacketRecived(EventPacketRecieve event) {
		  if(this.mode.getValue().equalsIgnoreCase("Tab") && event.getPacket() instanceof SPacketPlayerListItem) {
			  SPacketPlayerListItem packet = (SPacketPlayerListItem) event.getPacket();
			  for (SPacketPlayerListItem.AddPlayerData entrie : packet.getEntries()) {
				  if(packet.getAction() == SPacketPlayerListItem.Action.ADD_PLAYER) {
					  onPlayerJoin(entrie.getProfile());
				  } if(packet.getAction() == SPacketPlayerListItem.Action.REMOVE_PLAYER) {
					  onPlayerLeave(entrie.getProfile());
				  }
			  }
		  }
	  }
```
weird thing is, if i remove that then run it, there would be another error in the same class, somewhere else.

**Comment by ItzSomebody** [comment]
Looks like this might be an asm issue but it's really difficult to determine what's wrong without seeing the output jar.

**Comment by THEREALWWEFAN231** [comment]
Im pretty sure i found out the problem... 15 days later... in the gui, it would say process success, so i assumed its correct but i just read the console and it says

```
Do NOT report an issue about this exception unless you have absolutely made sure that the class reported missing exists in the library list you provided to Radon
[03/07/2019-21:55:33] ERROR: Error writing class me/THEREALWWEFAN231/wwefan/Modules/LogOutSpot.class.
me.itzsomebody.radon.exceptions.MissingClassException: com/mojang/brigadier/Message is missing in the classpath.
	at me.itzsomebody.radon.Radon.buildHierarchy(Radon.java:248)
	at me.itzsomebody.radon.Radon.getTree(Radon.java:227)
	at me.itzsomebody.radon.Radon$CustomClassWriter.isAssignableFrom(Radon.java:338)
	at me.itzsomebody.radon.Radon$CustomClassWriter.deriveCommonSuperName(Radon.java:307)
	at me.itzsomebody.radon.Radon$CustomClassWriter.getCommonSuperClass(Radon.java:292)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1198)
	at org.objectweb.asm.Frame.merge(Frame.java:1294)
	at org.objectweb.asm.Frame.merge(Frame.java:1239)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1617)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1553)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:810)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:690)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:426)
	at me.itzsomebody.radon.Radon.lambda$writeOutput$0(Radon.java:98)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at me.itzsomebody.radon.Radon.writeOutput(Radon.java:90)
	at me.itzsomebody.radon.Radon.partyTime(Radon.java:76)
	at me.itzsomebody.radon.gui.RadonGUI$1.doInBackground(RadonGUI.java:215)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Im pretty sure i was being stupid and did not import a library, if you wouldent mind? could you delete this issue and delete your reply to my other comment? lol.../:
