### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by fc13240** [ItzSomebody/Radon#83]
when encrypt large jar file such as 6GB, the program error:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at me.itzsomebody.radon.utils.IOUtils.toByteArray(IOUtils.java:44)
	at me.itzsomebody.radon.Radon.loadInput(Radon.java:229)
	at me.itzsomebody.radon.Radon.run(Radon.java:73)
	at me.itzsomebody.radon.Main.main(Main.java:81)

**Comment by ItzSomebody** [comment]
Closed for not following correct issue template.
