### ISSUE TITLE
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

### ISSUE THREAD

**Issue by nolove1337** [ItzSomebody/radon#99]
```
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at me.itzsomebody.radon.Main.main(Main.java:138)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```
I would like to know what needs to be written in the 2 arguments "examplekey"

**Comment by fuckyouthinkimboogieman** [comment]
Could you leave a jar of radon, please?

**Comment by ItzSomebody** [comment]
Sorry for the late response. Any update on this?

Would appreciate if you would use the issue template. If you're still having troubles, this looks like you just compiled a non-fatjar. Compile with the `shadowJar` task.
